"""Add summary column

Revision ID: 200e51358645
Revises: 102233d44451
Create Date: 2024-10-14 02:58:12.545866

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '200e51358645'
down_revision: Union[str, None] = '102233d44451'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('summary_pages', sa.Column('summary', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('summary_pages', 'summary')
    # ### end Alembic commands ###
